"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-2co=u2^z4y*@y_fq5wn8bjta2cchq5q%=j3qi(z5o$dwjys7+1',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() == 'true'

ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # intcomma -> "1.780" (LANGUAGE_CODE='tr' ayrımıyla)
    'katalog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# İKİ BAĞLANTI, AYNI POSTGRES SUNUCUSU, AYRI VERİTABANLARI.
#
# 'default' (metaks_web) sadece Django'nun kendi çerçeve tablolarını (auth,
# session, admin log) tutar. `python manage.py migrate` YALNIZCA buraya yazar.
#
# 'metaks' (depo_sistemi) gerçek METAKS verisidir. Bu bağlantı üzerinden sadece
# unmanaged modellerle (managed = False) zaten var olan view/tablolar okunur;
# buraya ASLA `migrate` çalıştırılmaz — şemanın otoritesi tamamen
# veritabani/sql/01_schema.sql + sql/migrations/'dadır.
#
# Ayrımın sebebi veritabanı MOTORU değil, ŞEMA EVRİM MEKANİZMASIDIR: veritabani/
# elle yazılmış numaralı SQL migration'larla (BEGIN/COMMIT, önce-test-sonra-uygula)
# yürüyor; Django'nun ORM migration'ları aynı fiziksel veritabanında bununla
# çakışmamalı. İki AYRI VERİTABANI bu ayrımı, tek bir motora inmenin bedeli
# olmadan sağlıyor.
#
# 2026-07-31'e kadar 'default' SQLite'tı (startproject varsayılanı). Postgres'e
# alındı çünkü: (1) db.sqlite3 ne git'te (gitignored) ne yedek_al.sh'de yer
# alıyordu, yani tüm kullanıcı hesapları tek diskte tek kopyaydı — artık aynı
# pg_dumpall ikisini birden kapsıyor; (2) SQLite yazarken dosyayı bütünüyle
# kilitler, Tailscale üzerinden çok cihazlı erişimde oturum yazımı için
# gereksiz bir kısıt. Taşınan veri: 1 kullanıcı (oturumlar bilerek taşınmadı,
# tek maliyeti yeniden giriş).

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.environ.get('WEB_DB_HOST', 'localhost'),
        'PORT': os.environ.get('WEB_DB_PORT', '5433'),
        'NAME': os.environ.get('WEB_DB_NAME', 'metaks_web'),
        'USER': os.environ.get('WEB_DB_USER', 'depo_admin'),
        'PASSWORD': os.environ.get('WEB_DB_PASSWORD', ''),
    },
    'metaks': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.environ.get('METAKS_DB_HOST', 'localhost'),
        'PORT': os.environ.get('METAKS_DB_PORT', '5433'),
        'NAME': os.environ.get('METAKS_DB_NAME', 'depo_sistemi'),
        'USER': os.environ.get('METAKS_DB_USER', 'depo_admin'),
        'PASSWORD': os.environ.get('METAKS_DB_PASSWORD', ''),
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# veritabani/'nin gorsel-sunucu servisi (nginx, port 8083) -> CLAUDE.md, Faz 5.
# Local geliştirmede localhost, üretimde Headscale/Tailscale adresine çekilir.
GORSEL_SUNUCU_BASE_URL = os.environ.get(
    'GORSEL_SUNUCU_BASE_URL', 'http://localhost:8083/urun-gorselleri/'
)

# Yukarıdakinin OKUMA (HTTP, tarayıcı) tarafı; bu ise YAZMA (dosya sistemi, Django
# süreci) tarafı — aynı dizinin iki farklı erişim yolu. nginx bu dizini `:ro`
# bağlıyor (veritabani/docker-compose.yml), yazan taraf host — yani bu Django süreci.
# Varsayılan artık repo-içi bir yol: BASE_DIR = <repo>/web olduğu için .parent
# repo kökü, oradan veritabani/ kardeş dizinine iniliyor. (2026-07-31 öncesi bu
# ayrı bir repoydu ve varsayılan `../metaks_DB/...` idi.) .env ile ezilebilir.
URUN_GORSEL_DIZINI = os.environ.get(
    'URUN_GORSEL_DIZINI', str(BASE_DIR.parent / 'veritabani' / 'images' / 'final' / 'products')
)

# Kimlik doğrulama. Kullanıcılar Django'nun kendi auth tablolarında, yani SQLite
# 'default' bağlantısında tutuluyor — paylaşımlı METAKS Postgres'ine dokunulmuyor.
#
# Sadece YAZMA sayfaları giriş istiyor (@login_required). Katalog ve stok listeleri
# herkese açık kalıyor: iç ağda, salt-okunur ve ön büroda hızla açılması gereken
# ekranlar. Yazma tarafında giriş bir tercih değil zorunluluk:
# stok_hareketleri.yapan_kullanici NOT NULL ve Postgres'e tek bir paylaşılan
# depo_admin kullanıcısıyla bağlanıldığı için "kim yaptı" bilgisi veritabanından
# okunamıyor, uygulamadan geçirilmek zorunda.
LOGIN_URL = 'katalog:giris'
LOGIN_REDIRECT_URL = 'katalog:ana_ekran'
LOGOUT_REDIRECT_URL = 'katalog:ana_ekran'
